project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!README.md"

format:
  html:
    theme: minty

website:
  title: "Big Year 2026 🦆🐦‍⬛"
  navbar:
    logo: "logo.png"
    background: primary
    left:
      - text: "Home"
        href: index.qmd
  favicon: "logo.png"