---
title: ""
page-layout: full
format:
  dashboard:
    css: styles.css
execute:
  echo: false
  warning: false
  message: false
project:
    execute-dir: project
---

```{r}
scripts <- list.files("scripts/", pattern = "\\.R$", full.names = TRUE)
invisible(lapply(scripts, source))

obs <- make_obs_table(
  users = "kjaeck,splendidfairywren", # Don't add commas between names!
  year = 2026,
  taxon_id = 3,
  user_pseudonyms = c(
    "Justine" = "splendidfairywren",
    "Alexander" = "kjaeck"
    ),
  only_species = TRUE, # Will remove higher order taxa
  ssp_to_sp = TRUE # Will replace all taxa info (Name, Conservation status, etc.) with the parent species
)
```

# Summary
::: {.stat-grid}
```{r results="asis"}
cat(make_author_stat_cards(obs))
```
:::

## Rote Liste species
::: {.stat-grid}
```{r results="asis"}
cat(make_rlz_stat_cards(obs))
```
:::

# Timeline
```{r}
plotly::ggplotly(plot_accum_species(obs))
```

# Map
```{r}
plot_obs_map(obs)
```

# Observations
```{r}
make_obs_html_table(obs)
```

# Species
## Row {.flow}
::: {.card title="Species table"}
```{r}
make_species_html_table(obs)
```
:::
## Row {.flow}
::: {.card title="Possible species"}
::: {.stat-grid}
```{r results="asis"}
# cat(make_species_coverage_card(obs))
```
:::
:::
